# Config file for automatic testing at travis-ci.org

language: python
python:
  - '3.6'
  - '2.7'

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

jobs:
  include:
    - stage: lambda
      language: python
      python: '3.6'
      before_script: cd cloudformation
      script: tox
